export interface FormatEntry {
  id: string;
  group: string;
  title: string;
  support: "existing" | "partial" | "proposal";
  note: string;
  source: string;
}

export const formats: FormatEntry[] = [
  {
    id: "user",
    group: "消息与正文",
    title: "用户消息",
    support: "existing",
    note: "右对齐气泡，支持复制、编辑、技能标签和附件元数据。",
    source: "apps/ui/src/components/MessageBubble.vue:185-247",
  },
  {
    id: "text",
    group: "消息与正文",
    title: "正文文本",
    support: "existing",
    note: "共享协议的 text part；由 Response 以流式 Markdown 渲染。",
    source: "packages/shared/src/types/agent.ts:19-35; apps/ui/src/components/MessageBubble.vue:264-283",
  },
  {
    id: "headings",
    group: "消息与正文",
    title: "标题",
    support: "existing",
    note: "基础 Markdown 的 h1-h6 已由现有 Response 渲染；没有独立消息 part。",
    source: "apps/ui/src/components/ai-elements/response/Response.vue:106-122; apps/ui/node_modules/vue-stream-markdown/README.md:19-30",
  },
  {
    id: "emphasis",
    group: "消息与正文",
    title: "强调",
    support: "partial",
    note: "粗体、斜体等由 Markdown 渲染器承载，不是协议类型。",
    source: "apps/ui/src/components/ai-elements/response/Response.vue:106-122; apps/ui/node_modules/vue-stream-markdown/README.md:19-30",
  },
  {
    id: "lists",
    group: "消息与正文",
    title: "列表",
    support: "partial",
    note: "普通 Markdown 列表可随正文渲染，当前没有列表专用 UI。",
    source: "apps/ui/src/components/ai-elements/response/Response.vue:106-122; apps/ui/node_modules/vue-stream-markdown/README.md:19-30",
  },
  {
    id: "checklist",
    group: "消息与正文",
    title: "清单",
    support: "partial",
    note: "正文中的任务清单有兜底解析；正式任务状态来自 tasks_updated 旁路事件。",
    source: "apps/ui/src/stores/chat.ts:112-140; packages/shared/src/types/agent.ts:246-250",
  },
  {
    id: "quote",
    group: "消息与正文",
    title: "段落引用",
    support: "existing",
    note: "基础 Markdown 的引用段落可由现有 Response 渲染；没有独立消息 part。",
    source: "apps/ui/src/components/ai-elements/response/Response.vue:106-122; apps/ui/node_modules/vue-stream-markdown/README.md:19-30",
  },
  {
    id: "links",
    group: "消息与正文",
    title: "链接",
    support: "existing",
    note: "基础 Markdown 链接可由现有 Response 渲染并带 URL 安全加固；没有专用链接卡片。",
    source: "apps/ui/node_modules/vue-stream-markdown/README.md:25-30; apps/ui/src/components/ai-elements/response/Response.vue:106-122",
  },
  {
    id: "table",
    group: "结构化内容",
    title: "表格",
    support: "existing",
    note: "基础 Markdown 表格可由现有 Response 渲染；没有独立表格 part。",
    source: "apps/ui/src/components/ai-elements/response/Response.vue:106-122; apps/ui/node_modules/vue-stream-markdown/README.md:21-27",
  },
  {
    id: "code",
    group: "结构化内容",
    title: "代码块",
    support: "existing",
    note: "Markdown code 扩展接入 Shiki，启用行号和 420px 限高。",
    source: "apps/ui/src/components/ai-elements/response/extensions.ts:68-80",
  },
  {
    id: "diff",
    group: "结构化内容",
    title: "差异",
    support: "partial",
    note: "Markdown 语言列表包含 diff；文件编辑行数另在工具行显示 +/-。",
    source: "apps/ui/src/components/ai-elements/response/extensions.ts:8-33; apps/ui/src/components/chat/ToolCallRow.vue:63-77",
  },
  {
    id: "math",
    group: "结构化内容",
    title: "数学公式",
    support: "partial",
    note: "当前未接入数学扩展；浏览器中数学字符按原文显示，尚未形成正常公式排版。",
    source: "apps/ui/src/components/ai-elements/response/extensions.ts:1-80; apps/ui/src/components/ai-elements/response/Response.vue:106-122",
  },
  {
    id: "mermaid",
    group: "结构化内容",
    title: "Mermaid 图",
    support: "partial",
    note: "当前只按代码源码展示，未接入 Mermaid 引擎，不能视为图形渲染已支持。",
    source: "apps/ui/src/components/ai-elements/response/extensions.ts:8-33; apps/ui/src/components/ai-elements/response/Response.vue:106-122",
  },
  {
    id: "html",
    group: "结构化内容",
    title: "HTML",
    support: "partial",
    note: "库支持安全 HTML 和自定义标签；是否启用仍取决于渲染器配置。",
    source: "apps/ui/node_modules/vue-stream-markdown/README.md:25-30",
  },
  {
    id: "callouts",
    group: "结构化内容",
    title: "Markdown 告警与提示",
    support: "partial",
    note: "基础引用可以展示提示文本；NOTE/TIP/WARNING/CAUTION 的专用语义样式仍待浏览器验证。",
    source: "apps/ui/src/components/ai-elements/response/Response.vue:106-122; apps/ui/src/components/ai-elements/response/extensions.ts:68-80",
  },
  {
    id: "footnotes",
    group: "结构化内容",
    title: "脚注",
    support: "existing",
    note: "浏览器验证已生成脚注引用与定义；当前仍属于 Markdown 渲染，不是独立协议 part。",
    source: "apps/ui/src/components/ai-elements/response/Response.vue:106-122; apps/ui/node_modules/vue-stream-markdown/README.md:19-30",
  },
  {
    id: "image",
    group: "富内容与边界",
    title: "Markdown 图片",
    support: "partial",
    note: "库支持图片流式加载和控件；没有独立 image part，不等于 Markdown 图片不支持。",
    source: "apps/ui/node_modules/vue-stream-markdown/README.md:21-27",
  },
  {
    id: "attachments",
    group: "富内容与边界",
    title: "附件",
    support: "partial",
    note: "附件元数据可渲染文件 chip，但 url 为空时不能形成真实预览；不是独立共享 message part。",
    source: "apps/ui/src/components/MessageBubble.vue:81-90,236-245; apps/ui/src/components/chat/ChatComposer.vue:139-145",
  },
  {
    id: "reasoning",
    group: "消息与正文",
    title: "推理",
    support: "existing",
    note: "共享协议的 reasoning part，独立折叠展示并记录耗时。",
    source: "packages/shared/src/types/agent.ts:20-22,52-68; apps/ui/src/components/MessageBubble.vue:264-276",
  },
  {
    id: "running",
    group: "交互与状态",
    title: "运行中",
    support: "existing",
    note: "流式消息尾部显示状态、loader 和运行时长。",
    source: "apps/ui/src/components/MessageBubble.vue:127-164,289-299",
  },
  {
    id: "read",
    group: "工具与过程",
    title: "读取",
    support: "existing",
    note: "readFile 映射为读取文件工具行，可展示目标文件并展开输出。",
    source: "apps/ui/src/components/chat/tool-part.ts:67-71; apps/ui/src/components/chat/ToolCallRow.vue:88-159",
  },
  {
    id: "directory",
    group: "工具与过程",
    title: "目录浏览",
    support: "existing",
    note: "listDir 映射为目录浏览工具行，目录目标带 folder 图标并可展示结果。",
    source: "apps/ui/src/components/chat/tool-part.ts:73-77; apps/ui/src/components/chat/ToolCallRow.vue:88-159",
  },
  {
    id: "search",
    group: "工具与过程",
    title: "搜索",
    support: "existing",
    note: "searchFiles 和 webSearch 都有动作标签与查询目标展示。",
    source: "apps/ui/src/components/chat/tool-part.ts:79-89",
  },
  {
    id: "terminal",
    group: "工具与过程",
    title: "终端",
    support: "existing",
    note: "runTerminal 显示终端动作和命令目标，结果可展开。",
    source: "apps/ui/src/components/chat/tool-part.ts:47-54; apps/ui/src/components/chat/ToolCallRow.vue:156-159",
  },
  {
    id: "edit",
    group: "工具与过程",
    title: "编辑",
    support: "existing",
    note: "editFile 显示文件目标和 +/- 行数，结果可展开。",
    source: "apps/ui/src/components/chat/tool-part.ts:61-65; apps/ui/src/components/chat/ToolCallRow.vue:63-77",
  },
  {
    id: "write",
    group: "工具与过程",
    title: "文件写入",
    support: "existing",
    note: "writeFile 映射为写入文件工具行，整文件写入只显示新增行数，结果可展开。",
    source: "apps/ui/src/components/chat/tool-part.ts:55-59; apps/ui/src/components/chat/ToolCallRow.vue:63-77",
  },
  {
    id: "web",
    group: "工具与过程",
    title: "网络",
    support: "existing",
    note: "webSearch 作为工具行存在；搜索结果没有独立正文/媒体协议。",
    source: "apps/ui/src/components/chat/tool-part.ts:85-89; packages/shared/src/types/agent.ts:203-229",
  },
  {
    id: "skill",
    group: "工具与过程",
    title: "技能",
    support: "existing",
    note: "loadSkill 有工具展示，用户消息也可带技能标签。",
    source: "apps/ui/src/components/chat/tool-part.ts:91-95; apps/ui/src/components/MessageBubble.vue:109-113,223-234",
  },
  {
    id: "mcp",
    group: "工具与过程",
    title: "MCP",
    support: "existing",
    note: "toolDisplay 对 mcp. 前缀提供 MCP 标签，仍复用通用工具 part。",
    source: "apps/ui/src/components/chat/tool-part.ts:101-105",
  },
  {
    id: "legacy-tool",
    group: "工具与过程",
    title: "旧版工具消息",
    support: "existing",
    note: "历史 role=tool 消息仍由 ToolCallCard 渲染；与新 tool part 行式展示并存。",
    source: "apps/ui/src/components/MessageBubble.vue:249-253; packages/shared/src/types/agent.ts:123-131",
  },
  {
    id: "tool-states",
    group: "工具与过程",
    title: "工具状态",
    support: "partial",
    note: "当前展示 running/ok/error；denied、percent 等准备态或进度字段尚未落成稳定视觉状态。",
    source: "packages/shared/src/types/agent.ts:23-35,183-229; apps/ui/src/components/chat/ToolCallRow.vue:146-148",
  },
  {
    id: "tool-output",
    group: "工具与过程",
    title: "工具输出",
    support: "existing",
    note: "工具结果摘要和 output 写回 part，展开后以文本或 JSON 显示。",
    source: "packages/shared/src/types/agent.ts:31-35,220-229; apps/ui/src/components/chat/ToolCallRow.vue:21-34,156-159",
  },
  {
    id: "approval",
    group: "交互与状态",
    title: "审批",
    support: "existing",
    note: "approval_request 是旁路事件，渲染为对话区顶部固定审批卡。",
    source: "packages/shared/src/types/agent.ts:185-201,230-237; apps/ui/src/components/chat/ApprovalCard.vue:28-67",
  },
  {
    id: "question",
    group: "交互与状态",
    title: "提问",
    support: "existing",
    note: "ask_user 是旁路事件，渲染为带选项/自由输入的顶部卡片。",
    source: "packages/shared/src/types/agent.ts:238-245; apps/ui/src/components/chat/AskUserCard.vue:63-145",
  },
  {
    id: "tasks",
    group: "交互与状态",
    title: "任务",
    support: "partial",
    note: "tasks_updated 更新会话信息卡；正文清单仅作兜底，不插入时间线快照。",
    source: "apps/ui/src/stores/chat.ts:112-140,300-304",
  },
  {
    id: "references",
    group: "交互与状态",
    title: "引用",
    support: "partial",
    note: "reference_found 写入会话参考面板；工具读写成功也会登记项目文件。",
    source: "apps/ui/src/stores/chat.ts:224-235,306-308; packages/shared/src/types/agent.ts:246-250",
  },
  {
    id: "notice",
    group: "交互与状态",
    title: "通知",
    support: "partial",
    note: "system 消息当前以全红错误样式呈现；没有统一 notice part 或中性提示层级。",
    source: "apps/ui/src/components/MessageBubble.vue:255-262; packages/shared/src/types/agent.ts:170-180",
  },
  {
    id: "error",
    group: "交互与状态",
    title: "错误",
    support: "existing",
    note: "error 旁路事件写入 lastError，并在时间线顶部以 alert 展示。",
    source: "apps/ui/src/stores/chat.ts:279-283; apps/ui/src/components/chat/ChatTimeline.vue:107-114",
  },
  {
    id: "lifecycle",
    group: "交互与状态",
    title: "生命周期终态",
    support: "partial",
    note: "合约包含暂停及 stop/cancelled/error/max_steps；当前缺少一致的历史终态标识与原因展示。",
    source: "packages/shared/src/types/agent.ts:170-180,251-253; apps/ui/src/stores/chat.ts:266-299",
  },
  {
    id: "usage",
    group: "交互与状态",
    title: "步骤号与 Token 用量",
    support: "partial",
    note: "step_start/usage 事件已有合约；当前 store 只保留 inputTokens 用于上下文比例，尚无步骤号和完整用量展示。",
    source: "packages/shared/src/types/agent.ts:247-248; apps/ui/src/stores/chat.ts:95-98,284-286",
  },
  {
    id: "completion",
    group: "交互与状态",
    title: "完成",
    support: "partial",
    note: "done 事件结束运行并清理状态，当前没有独立完成卡片。",
    source: "packages/shared/src/types/agent.ts:252-253; apps/ui/src/stores/chat.ts:287-299",
  },
  {
    id: "artifacts",
    group: "富内容与边界",
    title: "产物",
    support: "proposal",
    note: "当前没有独立 artifact part；文件写入结果通过工具行和右侧文件面板体现。",
    source: "apps/ui/src/components/chat/ToolCallRow.vue:80-84; packages/shared/src/types/agent.ts:19-35",
  },
  {
    id: "subagent",
    group: "工具与过程",
    title: "并行子任务",
    support: "proposal",
    note: "当前没有专用 subagent 事件或时间线 part；并行子任务展示属于拟议协议能力。",
    source: "packages/shared/src/types/agent.ts:203-253; apps/ui/src/components/chat/tool-part.ts:101-105",
  },
  {
    id: "streaming",
    group: "消息与正文",
    title: "流式边界",
    support: "partial",
    note: "正文增量已有库和 ResizeObserver 兜底；未闭合代码、半张表和实时文本仍需边界验收。",
    source: "packages/shared/src/types/agent.ts:40-118; apps/ui/src/components/ai-elements/response/Response.vue:106-122; apps/ui/src/components/chat/ChatTimeline.vue:47-77",
  },
  {
    id: "media",
    group: "富内容与边界",
    title: "媒体",
    support: "proposal",
    note: "当前没有独立音视频 part；图片能力已有独立条目，音视频展示先作为拟议能力。",
    source: "apps/ui/src/components/MessageBubble.vue:37-43,81-89; packages/shared/src/types/agent.ts:19-35",
  },
  {
    id: "boundaries",
    group: "富内容与边界",
    title: "边界",
    support: "existing",
    note: "消息区、顶部交互卡、Markdown 正文、工具行和会话面板已有边界；尚无统一语义层。",
    source: "apps/ui/src/components/chat/ChatTimeline.vue:79-122; apps/ui/src/components/MessageBubble.vue:264-300",
  },
];
