import { caps, EFF_STD, MEDIA, REASON, TOOL, VISION } from "./model-catalog-seed";

import type { CatalogSeed } from "./model-catalog-seed";

export const ANTHROPIC_SEEDS: CatalogSeed[] = [
  {
    vendorId: "anthropic",
    vendor: "anthropic",
    modelKey: "claude-fable-5-1",
    id: "claude-fable-5-1",
    name: "Claude Fable 5.1",
    capabilities: caps({
      ...REASON,
      ...VISION,
      ...TOOL,
      contextWindow: 1_000_000,
      maxOutputTokens: 128_000,
      reasoningEfforts: [...EFF_STD],
    }),
  },
  {
    vendorId: "anthropic",
    vendor: "anthropic",
    modelKey: "claude-opus-5",
    id: "claude-opus-5",
    name: "Claude Opus 5",
    capabilities: caps({
      ...REASON,
      ...VISION,
      ...TOOL,
      contextWindow: 1_000_000,
      maxOutputTokens: 128_000,
      reasoningEfforts: [...EFF_STD],
    }),
  },
  {
    vendorId: "anthropic",
    vendor: "anthropic",
    modelKey: "claude-sonnet-5",
    id: "claude-sonnet-5",
    name: "Claude Sonnet 5",
    capabilities: caps({
      ...REASON,
      ...VISION,
      ...TOOL,
      contextWindow: 1_000_000,
      maxOutputTokens: 128_000,
      reasoningEfforts: [...EFF_STD],
    }),
  },
  {
    vendorId: "anthropic",
    vendor: "anthropic",
    modelKey: "claude-haiku-4-5",
    id: "claude-haiku-4-5",
    name: "Claude Haiku 4.5",
    capabilities: caps({
      ...VISION,
      ...TOOL,
      contextWindow: 200_000,
      maxOutputTokens: 64_000,
    }),
  },
  {
    vendorId: "anthropic",
    vendor: "anthropic",
    modelKey: "claude-opus-4-8",
    id: "claude-opus-4-8",
    name: "Claude Opus 4.8",
    capabilities: caps({
      ...REASON,
      ...VISION,
      ...TOOL,
      contextWindow: 1_000_000,
      maxOutputTokens: 128_000,
      reasoningEfforts: [...EFF_STD],
    }),
  },
  {
    vendorId: "anthropic",
    vendor: "anthropic",
    modelKey: "claude-sonnet-4-6",
    id: "claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    capabilities: caps({
      ...REASON,
      ...VISION,
      ...TOOL,
      contextWindow: 1_000_000,
      maxOutputTokens: 128_000,
      reasoningEfforts: [...EFF_STD],
    }),
  },
  {
    vendorId: "anthropic",
    vendor: "anthropic",
    modelKey: "claude-haiku-4-5-20251001",
    id: "claude-haiku-4-5-20251001",
    name: "Claude Haiku 4.5 (dated)",
    capabilities: caps({
      ...VISION,
      ...TOOL,
      contextWindow: 200_000,
      maxOutputTokens: 64_000,
    }),
  },
];

export const GOOGLE_SEEDS: CatalogSeed[] = [
  {
    vendorId: "google",
    vendor: "google",
    modelKey: "gemini-2.5-pro",
    id: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    capabilities: caps({
      ...REASON,
      ...VISION,
      ...TOOL,
      ...MEDIA,
      contextWindow: 1_048_576,
      maxOutputTokens: 65_536,
      reasoningEfforts: [...EFF_STD],
    }),
  },
  {
    vendorId: "google",
    vendor: "google",
    modelKey: "gemini-2.5-flash",
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    capabilities: caps({
      ...VISION,
      ...TOOL,
      ...MEDIA,
      contextWindow: 1_048_576,
      maxOutputTokens: 65_536,
    }),
  },
  {
    vendorId: "google",
    vendor: "google",
    modelKey: "gemini-2.5-flash-lite",
    id: "gemini-2.5-flash-lite",
    name: "Gemini 2.5 Flash-Lite",
    capabilities: caps({
      ...VISION,
      ...TOOL,
      contextWindow: 1_048_576,
      maxOutputTokens: 65_536,
    }),
  },
  {
    vendorId: "google",
    vendor: "google",
    modelKey: "gemini-2.0-flash",
    id: "gemini-2.0-flash",
    name: "Gemini 2.0 Flash",
    capabilities: caps({
      ...VISION,
      ...TOOL,
      ...MEDIA,
      contextWindow: 1_048_576,
      maxOutputTokens: 8_192,
    }),
  },
];

export const DEEPSEEK_SEEDS: CatalogSeed[] = [
  {
    vendorId: "deepseek",
    vendor: "deepseek",
    modelKey: "deepseek-flash",
    id: "deepseek-flash",
    name: "DeepSeek Flash",
    capabilities: caps({
      ...REASON,
      ...VISION,
      ...TOOL,
      contextWindow: 1_000_000,
      maxOutputTokens: 384_000,
      reasoningEfforts: ["low", "medium", "high", "xhigh", "max"],
    }),
  },
  {
    vendorId: "deepseek",
    vendor: "deepseek",
    modelKey: "deepseek-v4-flash",
    id: "deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    capabilities: caps({
      ...REASON,
      ...VISION,
      ...TOOL,
      contextWindow: 1_000_000,
      maxOutputTokens: 384_000,
      reasoningEfforts: ["low", "medium", "high", "xhigh", "max"],
    }),
  },
  {
    vendorId: "deepseek",
    vendor: "deepseek",
    modelKey: "deepseek-v4-pro",
    id: "deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    capabilities: caps({
      ...REASON,
      ...TOOL,
      contextWindow: 1_000_000,
      maxOutputTokens: 384_000,
      reasoningEfforts: [...EFF_STD],
    }),
  },
  {
    vendorId: "deepseek",
    vendor: "deepseek",
    modelKey: "deepseek-chat",
    id: "deepseek-chat",
    name: "DeepSeek Chat",
    capabilities: caps({ ...TOOL, contextWindow: 128_000, maxOutputTokens: 8_192 }),
  },
  {
    vendorId: "deepseek",
    vendor: "deepseek",
    modelKey: "deepseek-reasoner",
    id: "deepseek-reasoner",
    name: "DeepSeek Reasoner",
    capabilities: caps({
      ...REASON,
      ...TOOL,
      contextWindow: 128_000,
      maxOutputTokens: 32_768,
      reasoningEfforts: [...EFF_STD],
    }),
  },
];
