import { caps, EFF_ALL, EFF_STD, MEDIA, REASON, TOOL, VISION } from "./model-catalog-seed";

import type { CatalogSeed } from "./model-catalog-seed";
import type { ModelCapabilities } from "@zen/shared";

export const OPENAI_SEEDS: CatalogSeed[] = [
  {
    vendorId: "openai",
    vendor: "openai",
    modelKey: "gpt-6-astra",
    id: "gpt-6-astra",
    name: "GPT-6 Astra",
    capabilities: caps({
      ...REASON,
      ...VISION,
      ...TOOL,
      ...MEDIA,
      contextWindow: 1_050_000,
      maxOutputTokens: 128_000,
      reasoningEfforts: [...EFF_ALL],
    }),
  },
  {
    vendorId: "openai",
    vendor: "openai",
    modelKey: "gpt-5.6-sol",
    id: "gpt-5.6-sol",
    name: "GPT-5.6 Sol",
    capabilities: caps({
      ...REASON,
      ...VISION,
      ...TOOL,
      contextWindow: 1_050_000,
      maxOutputTokens: 128_000,
      reasoningEfforts: ["minimal", ...EFF_ALL] as ModelCapabilities["reasoningEfforts"],
    }),
  },
  {
    vendorId: "openai",
    vendor: "openai",
    modelKey: "gpt-5.6",
    id: "gpt-5.6",
    name: "GPT-5.6",
    capabilities: caps({
      ...REASON,
      ...VISION,
      ...TOOL,
      contextWindow: 1_050_000,
      maxOutputTokens: 128_000,
      reasoningEfforts: ["minimal", ...EFF_ALL] as ModelCapabilities["reasoningEfforts"],
    }),
  },
  {
    vendorId: "openai",
    vendor: "openai",
    modelKey: "gpt-5.6-terra",
    id: "gpt-5.6-terra",
    name: "GPT-5.6 Terra",
    capabilities: caps({
      ...REASON,
      ...VISION,
      ...TOOL,
      contextWindow: 1_050_000,
      maxOutputTokens: 128_000,
      reasoningEfforts: ["minimal", ...EFF_ALL] as ModelCapabilities["reasoningEfforts"],
    }),
  },
  {
    vendorId: "openai",
    vendor: "openai",
    modelKey: "gpt-5.6-luna",
    id: "gpt-5.6-luna",
    name: "GPT-5.6 Luna",
    capabilities: caps({
      ...REASON,
      ...VISION,
      ...TOOL,
      contextWindow: 1_050_000,
      maxOutputTokens: 128_000,
      reasoningEfforts: ["minimal", ...EFF_ALL] as ModelCapabilities["reasoningEfforts"],
    }),
  },
  {
    vendorId: "openai",
    vendor: "openai",
    modelKey: "gpt-5",
    id: "gpt-5",
    name: "GPT-5",
    capabilities: caps({
      ...REASON,
      ...VISION,
      ...TOOL,
      ...MEDIA,
      contextWindow: 400_000,
      maxOutputTokens: 128_000,
      reasoningEfforts: [...EFF_STD],
    }),
  },
  {
    vendorId: "openai",
    vendor: "openai",
    modelKey: "gpt-5-mini",
    id: "gpt-5-mini",
    name: "GPT-5 mini",
    capabilities: caps({
      ...REASON,
      ...VISION,
      ...TOOL,
      contextWindow: 400_000,
      maxOutputTokens: 128_000,
      reasoningEfforts: [...EFF_STD],
    }),
  },
  {
    vendorId: "openai",
    vendor: "openai",
    modelKey: "gpt-4.1",
    id: "gpt-4.1",
    name: "GPT-4.1",
    capabilities: caps({
      ...VISION,
      ...TOOL,
      contextWindow: 1_047_576,
      maxOutputTokens: 32_768,
    }),
  },
  {
    vendorId: "openai",
    vendor: "openai",
    modelKey: "gpt-4o",
    id: "gpt-4o",
    name: "GPT-4o",
    capabilities: caps({
      ...VISION,
      ...TOOL,
      ...MEDIA,
      contextWindow: 128_000,
      maxOutputTokens: 16_384,
    }),
  },
  {
    vendorId: "openai",
    vendor: "openai",
    modelKey: "gpt-4o-mini",
    id: "gpt-4o-mini",
    name: "GPT-4o mini",
    capabilities: caps({
      ...VISION,
      ...TOOL,
      contextWindow: 128_000,
      maxOutputTokens: 16_384,
    }),
  },
  {
    vendorId: "openai",
    vendor: "openai",
    modelKey: "o3",
    id: "o3",
    name: "o3",
    capabilities: caps({
      ...REASON,
      ...VISION,
      ...TOOL,
      contextWindow: 200_000,
      maxOutputTokens: 100_000,
      reasoningEfforts: [...EFF_STD],
    }),
  },
  {
    vendorId: "openai",
    vendor: "openai",
    modelKey: "o4-mini",
    id: "o4-mini",
    name: "o4-mini",
    capabilities: caps({
      ...REASON,
      ...VISION,
      ...TOOL,
      contextWindow: 200_000,
      maxOutputTokens: 100_000,
      reasoningEfforts: [...EFF_STD],
    }),
  },
];
