import { caps, EFF_STD, MEDIA, REASON, TOOL, VISION } from "./model-catalog-seed";

import type { CatalogSeed } from "./model-catalog-seed";

export const MIMO_SEEDS: CatalogSeed[] = [
  {
    vendorId: "mimo",
    vendor: "mimo",
    modelKey: "mimo-v2.5-pro",
    id: "mimo-v2.5-pro",
    name: "MiMo V2.5 Pro",
    capabilities: caps({
      ...REASON,
      ...VISION,
      ...TOOL,
      contextWindow: 256_000,
      maxOutputTokens: 64_000,
      reasoningEfforts: ["low", "medium", "high", "xhigh"],
    }),
  },
  {
    vendorId: "mimo",
    vendor: "mimo",
    modelKey: "mimo-v2.5",
    id: "mimo-v2.5",
    name: "MiMo V2.5",
    capabilities: caps({
      ...VISION,
      ...TOOL,
      contextWindow: 256_000,
      maxOutputTokens: 64_000,
    }),
  },
];

export const ZHIPU_SEEDS: CatalogSeed[] = [
  {
    vendorId: "zhipu",
    vendor: "zhipu",
    modelKey: "glm-5.3",
    id: "glm-5.3",
    name: "GLM-5.3",
    capabilities: caps({
      ...REASON,
      ...TOOL,
      contextWindow: 1_000_000,
      maxOutputTokens: 128_000,
      reasoningEfforts: [...EFF_STD],
    }),
  },
  {
    vendorId: "zhipu",
    vendor: "zhipu",
    modelKey: "glm-5.3-flash",
    id: "glm-5.3-flash",
    name: "GLM-5.3-Flash",
    capabilities: caps({
      ...REASON,
      ...VISION,
      ...TOOL,
      ...MEDIA,
      contextWindow: 1_000_000,
      maxOutputTokens: 128_000,
      reasoningEfforts: [...EFF_STD],
    }),
  },
  {
    vendorId: "zhipu",
    vendor: "zhipu",
    modelKey: "glm-5.2",
    id: "glm-5.2",
    name: "GLM-5.2",
    capabilities: caps({
      ...REASON,
      ...TOOL,
      contextWindow: 1_000_000,
      maxOutputTokens: 128_000,
      reasoningEfforts: [...EFF_STD],
    }),
  },
  {
    vendorId: "zhipu",
    vendor: "zhipu",
    modelKey: "glm-5.1",
    id: "glm-5.1",
    name: "GLM-5.1",
    capabilities: caps({
      ...REASON,
      ...TOOL,
      contextWindow: 200_000,
      maxOutputTokens: 128_000,
      reasoningEfforts: [...EFF_STD],
    }),
  },
  {
    vendorId: "zhipu",
    vendor: "zhipu",
    modelKey: "glm-5",
    id: "glm-5",
    name: "GLM-5",
    capabilities: caps({
      ...REASON,
      ...TOOL,
      contextWindow: 200_000,
      maxOutputTokens: 128_000,
      reasoningEfforts: [...EFF_STD],
    }),
  },
  {
    vendorId: "zhipu",
    vendor: "zhipu",
    modelKey: "glm-4.7",
    id: "glm-4.7",
    name: "GLM-4.7",
    capabilities: caps({
      ...REASON,
      ...TOOL,
      contextWindow: 200_000,
      maxOutputTokens: 128_000,
      reasoningEfforts: [...EFF_STD],
    }),
  },
  {
    vendorId: "zhipu",
    vendor: "zhipu",
    modelKey: "glm-4.6",
    id: "glm-4.6",
    name: "GLM-4.6",
    capabilities: caps({
      ...REASON,
      ...TOOL,
      contextWindow: 200_000,
      maxOutputTokens: 128_000,
      reasoningEfforts: [...EFF_STD],
    }),
  },
  {
    vendorId: "zhipu",
    vendor: "zhipu",
    modelKey: "glm-4.5",
    id: "glm-4.5",
    name: "GLM-4.5",
    capabilities: caps({
      ...REASON,
      ...TOOL,
      contextWindow: 128_000,
      maxOutputTokens: 96_000,
      reasoningEfforts: [...EFF_STD],
    }),
  },
  {
    vendorId: "zhipu",
    vendor: "zhipu",
    modelKey: "glm-5v-turbo",
    id: "glm-5v-turbo",
    name: "GLM-5V-Turbo",
    capabilities: caps({
      ...REASON,
      ...VISION,
      ...TOOL,
      contextWindow: 200_000,
      maxOutputTokens: 128_000,
      reasoningEfforts: [...EFF_STD],
    }),
  },
  {
    vendorId: "zhipu",
    vendor: "zhipu",
    modelKey: "glm-4.6v",
    id: "glm-4.6v",
    name: "GLM-4.6V",
    capabilities: caps({
      ...VISION,
      ...TOOL,
      contextWindow: 128_000,
      maxOutputTokens: 32_000,
    }),
  },
];

export const QWEN_SEEDS: CatalogSeed[] = [
  {
    vendorId: "qwen",
    vendor: "qwen",
    modelKey: "qwen3.8-max",
    id: "qwen3.8-max",
    name: "Qwen3.8-Max",
    capabilities: caps({
      ...REASON,
      ...VISION,
      ...TOOL,
      contextWindow: 256_000,
      maxOutputTokens: 65_536,
      reasoningEfforts: [...EFF_STD],
    }),
  },
  {
    vendorId: "qwen",
    vendor: "qwen",
    modelKey: "qwen3.7-plus",
    id: "qwen3.7-plus",
    name: "Qwen3.7-Plus",
    capabilities: caps({
      ...VISION,
      ...TOOL,
      contextWindow: 256_000,
      maxOutputTokens: 65_536,
    }),
  },
  {
    vendorId: "qwen",
    vendor: "qwen",
    modelKey: "qwen3.8-flash",
    id: "qwen3.8-flash",
    name: "Qwen3.8-Flash",
    capabilities: caps({
      ...TOOL,
      contextWindow: 256_000,
      maxOutputTokens: 65_536,
    }),
  },
  {
    vendorId: "qwen",
    vendor: "qwen",
    modelKey: "qwen3-max",
    id: "qwen3-max",
    name: "Qwen3-Max",
    capabilities: caps({
      ...REASON,
      ...TOOL,
      contextWindow: 256_000,
      maxOutputTokens: 32_768,
      reasoningEfforts: [...EFF_STD],
    }),
  },
  {
    vendorId: "qwen",
    vendor: "qwen",
    modelKey: "qwen3-coder-plus",
    id: "qwen3-coder-plus",
    name: "Qwen3-Coder-Plus",
    capabilities: caps({ ...TOOL, contextWindow: 256_000, maxOutputTokens: 65_536 }),
  },
  {
    vendorId: "qwen",
    vendor: "qwen",
    modelKey: "qwen3.5-omni-plus",
    id: "qwen3.5-omni-plus",
    name: "Qwen3.5-Omni-Plus",
    capabilities: caps({
      ...VISION,
      ...TOOL,
      ...MEDIA,
      contextWindow: 256_000,
      maxOutputTokens: 32_768,
    }),
  },
  {
    vendorId: "qwen",
    vendor: "qwen",
    modelKey: "qwen2.5-coder-32b-instruct",
    id: "qwen2.5-coder-32b-instruct",
    name: "Qwen2.5 Coder 32B",
    capabilities: caps({ ...TOOL, contextWindow: 131_072, maxOutputTokens: 8_192 }),
  },
];
